---
site_name: Ruby Learning
site_type: ruby
author: Typophic User
description: A beautiful static website for learning Ruby
url: https://rubylearning.in
theme:
  default: rubylearning
  sections:
    blog: rubylearning
    posts: rubylearning
    pages: rubylearning
permalink_style: pretty
date_format: "%B %-d, %Y"
markdown_extensions:
- tables
- fenced_code_blocks
- autolink
repository:
  url: git@github.com:metacritical/rubylearning.git
  branch: main
  deploy_branch: gh-pages
collections:
  posts:
    permalink: /blog/:slug/
