---
site_name: Ruby Learning
site_type: ruby
author: Typophic User
description: A beautiful static website for learning Ruby
url: https://rubylearning.in
theme:
  default: rubylearning
  sections: {}
permalink_style: pretty
date_format: "%B %-d, %Y"
markdown_extensions:
- tables
- fenced_code_blocks
- autolink
protocss:
  css:
  - themes/rubylearning/css/*.css
  - themes/hydejack/assets/css/hydejack-9.2.1.css
repository:
  url: git@github.com:metacritical/rubylearning.git
  branch: main
  deploy_branch: gh-pages
collections:
  posts:
    permalink: "/blog/:slug/"
pipeline:
  steps:
  - rubocop_ruby_blocks
  - hash_blocks
  - mermaid_blocks
  - ditaa_blocks
  - ruby_exec
  - practice_blocks
  - ruby_pre_blocks
  - markdown
